export default {
    POSTS_GET_ATTEMPT: 'POSTS_GET_ATTEMPT',
    POSTS_GET_SUCCESS: 'POSTS_GET_SUCCESS',

    POSTS_GET_DETAILS_ATTEMPT: 'POSTS_GET_DETAILS_ATTEMPT',
    POSTS_GET_DETAILS_SUCCESS: 'POSTS_GET_DETAILS_SUCCESS',
};
